### ISSUE TITLE
Do you plan to put any implementation of COCO-GAN?

### ISSUE THREAD

**Issue by johngull** [hubert0527/COCO-GAN#1]

**Comment by hubert0527** [comment]
Thanks for your interest.
Yes, we will release the training code as well as some checkpoints.
But given we are still cleaning the code and the paper is still under review, it may take us some time.
Please stay tuned :)

**Comment by johngull** [comment]
While we are waiting for official code release. Can you please explain what is the `y` input on the generator and discriminator architectures in your paper? Is it full latent vector "noise" + coordinates?

**Comment by hubert0527** [comment]
(Disclaimer: We didn't put too much effort on analyzing the effect of this design choice)

**In our implementation:**
For the generator, `y` is `concat(z, coordinates)`. In short, such a design aims to provide the generator with hints about what **global** features should be presented in the final full image.
For the discriminator, `y` is `coordinates` only. Since we only care about whether the macro patches match the conditional distribution in different coordinates.

If you have further detailed implementation problems, feel free to send private emails :)

**Comment by mchalecki** [comment]
Any progress on releasing training code ?

**Comment by mukaddesau** [comment]
I am also looking forward to seeing the code. Do you have a plan to publish your implementation very soon? 
Bests.

**Comment by giering** [comment]
Fantastic work! I'm looking forward to taking it for a test drive.

**Comment by shaanrockz** [comment]
Interesting ! Looking forward to see your code. When are you planning to publish your code?
Regards

**Comment by hubert0527** [comment]
Hi all,

Thanks for your interests, I'm working on cleaning up the codebase now.
However, I got a little busy recently, and I can only work on this with my spare time. 
So I guess it will take me a couple of weeks.
Please stay tuned :)

Best,
Hubert

**Comment by donghaoye** [comment]
Interesting ! Looking forward to see your code.

**Comment by du-91** [comment]
Hello, 

Excellent! We are waiting for your code. Thank you for the effort!

**Comment by zhuhaozh** [comment]
Interesting work! Looking forward to your codes.

**Comment by damlasena** [comment]
Really good work! I would like to know when you plan to publish the code. So excited to see it.

**Comment by jakubLangr** [comment]
Really looking forward to seeing the code!

**Comment by dudoeu** [comment]
I loved your project. Would you please publish your code soon? It would be great to train my data-set with this extraordinary work. Thank you in advance.

**Comment by hubert0527** [comment]
Sincerely sorry for the long waiting, the code is publicitly available now.
