### ISSUE TITLE
Using a custom dataset

### ISSUE THREAD

**Issue by Matty0512** [hubert0527/COCO-GAN#10]
I'm having OOM issues trying to run a custom dataset of 256x256 resolution. Apart from creating a YAML config file for my dataset does anything else need to implemented for this to work?

**Comment by hubert0527** [comment]
You can try to reduce the batch size first, depending on your GPU memory size.

Since `gpu_options.allow_growth` is set to `True`, you can first set the batch size to a very small size (such as 4 or 8), and see what is the portion of the GPU memory is occupied (with `nvidia-smi`). Then you can decide the maximum batch size your GPU can accommodate.

In a more advanced way, if you are sure that your images have less dependency between patches that are far away, you can try to tune the micro patch size and macro patch size a bit. Such as setting them both to a smaller value (such as 32x32 and 64x64, respectively, for your 256x256 images), but I am not entirely sure about how Tensorflow will deal with it in the backend. 

Lastly, a brute-force solution is resizing your images to a smaller size (such as 128x128), do the training and generation, then upsample the results back to 256x256. It will get your training a lot faster, requires less memory, and the resulting quality will still be good (though a bit blurry).
