### ISSUE TITLE
Add a requirements.txt?

### ISSUE THREAD

**Issue by waydegilliam** [hubert0527/COCO-GAN#12]
I'm just trying to run all the preprocessing/training on the CelebA dataset, and so far I'm missing several packages besides just tensorflow. Some of the utilities with `scipy` have been deprecated at this point in time, so I've had to go through and find the correct versions of certain packages including that one to get things working. Would greatly appreciate a requirements.txt or conda environment.yaml file. Thanks!

**Comment by hubert0527** [comment]
Thanks for the suggestion!
I didn't expect the environmental issue can be that annoying.

I personally do not prefer using `requirements` files with TF, since some TF versions are frequently missing in some OS system configs.
As an alternative, I updated the `README` with the conda command that can install all the required packages.
```
conda install tensorflow-gpu==1.13.1 scipy==1.1.0 pyyaml==5.3 pillow==6.0.0 tqdm
```
